# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iChart', '0005_auto_20171210_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sheet_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('info', models.TextField(default='{}', max_length=65535)),
                ('content', models.TextField(default='{}', max_length=65535)),
            ],
        ),
    ]
